//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Start,End,Type,EmployeeId
        ///1,15/09/2020,03/10/2020,1,17
        ///2,05/04/2020,13/05/2020,2,9
        ///3,19/03/2021,21/04/2021,2,7
        ///4,24/04/2021,17/05/2021,1,6
        ///5,07/09/2020,23/09/2020,2,2
        ///6,30/11/2020,31/12/2020,2,9
        ///7,01/01/2020,28/01/2020,1,19
        ///8,26/05/2020,26/06/2020,2,6
        ///9,20/01/2020,28/02/2020,2,15
        ///10,29/12/2020,01/01/2021,1,4
        ///11,13/01/2021,19/02/2021,1,7
        ///12,13/02/2020,20/02/2020,2,19
        ///13,02/11/2020,22/11/2020,2,12
        ///14,11/01/2021,02/02/2021,2,16
        ///15,09/03/2021,12/04/2021,2,3
        ///16,12/12/2020,13/12/2020,2,11
        ///17,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Absences {
            get {
                return ResourceManager.GetString("Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,EmployeeNumber,Name,Department
        ///1,1,Sherri Merrick,Development
        ///2,2,Audrey Fraizer,Sales
        ///3,3,Janay Hickerson,Marketing
        ///4,4,Darren Hammel,Marketing
        ///5,5,Clare Teamer,Sales
        ///6,6,Rosann Harvill,Development
        ///7,7,Glennis Dahmen,Development
        ///8,8,Stefan O&apos;Dwyer,Sales
        ///9,9,Mauro Freas,Sales
        ///10,10,Almeda Heft,Development
        ///11,11,Rhiannon Calabria,Development
        ///12,12,Haywood Saenz,Development
        ///13,13,Lester Pinheiro,Development
        ///14,14,Alvaro Alonzo,QA
        ///15,15,Shirleen Rue,QA
        ///16,16,Jewel Cone,Development
        ///17,17,Kal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
    }
}
